# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Optimización de memoria
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Soporte para AndroidX
android.useAndroidX=true

# Estilo de código oficial de Kotlin
kotlin.code.style=official

# Reducción de tamaño de clases R (No transitivas)
android.nonTransitiveRClass=true

# Forzar R8 a modo estricto (mejor para seguridad y tamaño)
android.r8.strictFullModeForKeepRules=true

# Optimización de dependencias
android.dependency.useConstraints=true
